apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: janl61pl8-go 
  janus-idp.io/tekton: janl61pl8-go
  backstage.io/kubernetes-id: janl61pl8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: janl61pl8-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml